### ISSUE TITLE
Reading play/pause status?

### ISSUE THREAD

**Issue by cagdassalur** [kirtan-shah/nowplaying-cli#3]
Is  there a possibility with this tool?

**Comment by kirtan-shah** [comment]
I don't think this is possible with the current APIs.
At first I wanted to read play/pause status as well because I wanted to implement the functionality of "if something is playing, then pause it." But this functionality can be implemented with `nowplaying-cli pause` because pausing already paused content does nothing.

**Comment by cagdassalur** [comment]
Thanks a lot for the answer. My main use case was that i wanted to show current media playing on my status only when it's played and not paused. Or maybe just put a play/pause icon, but yeah.

**Comment by frypf** [comment]
Sorry for weighing in on another closed issue, but it struck me that you maybe could check whether `kMRMediaRemoteNowPlayingInfoPlaybackRate > 0` for this?

**Comment by kirtan-shah** [comment]
Good idea, it seems like the behavior is dependent on the app though. Spotify gives me 1/null when play/pause but youtube on firefox stays stuck at 1 whether play/pause. Probably best left to the user to interpret
